---
abstract: 'Override the LWP::UserAgent to return canned responses for testing'
author:
  - 'Douglas Christopher Wilson <doug@somethingdoug.com>'
build_requires:
  HTTP::Request: 0
  HTTP::Response: 0
  IO::String: 0
  LWP::UserAgent: 0
  Test::Fatal: 0
  Test::More: 0
  Test::Requires: 0.02
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Override-UserAgent
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  Test::Override::UserAgent:
    file: lib/Test/Override/UserAgent.pm
    version: 0.003
  Test::Override::UserAgent::Scope:
    file: lib/Test/Override/UserAgent/Scope.pm
    version: 0.003
requires:
  Carp: 0
  Clone: 0
  HTTP::Config: 5.815
  HTTP::Date: 0
  HTTP::Headers: 0
  HTTP::Response: 0
  HTTP::Status: 5.817
  LWP::Protocol: 0
  LWP::UserAgent: 0
  Scalar::Util: 0
  Sub::Install: 0.90
  Sub::Override: 0
  Try::Tiny: 0
  URI: 0
  namespace::clean: 0.04
  perl: 5.008001
resources:
  homepage: http://github.com/dougwilson/perl5-test-override-useragent/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/dougwilson/perl5-test-override-useragent.git
version: 0.003
