---
abstract: 'Override the LWP::UserAgent to return canned'
author:
  - 'Douglas Christopher Wilson <doug@somethingdoug.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  HTTP::Request: 0
  HTTP::Response: 0
  IO::String: 0
  Test::Exception: 0.03
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Override-UserAgent
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  Test::Override::UserAgent:
    file: lib/Test/Override/UserAgent.pm
    version: 0.001
requires:
  Carp: 0
  HTTP::Date: 0
  HTTP::Headers: 0
  HTTP::Response: 0
  HTTP::Status: 5.817
  LWP::UserAgent: 0
  Scalar::Util: 0
  Sub::Install: 0.90
  Sub::Override: 0
  URI: 0
  namespace::clean: 0.04
  perl: 5.8.1
resources:
  homepage: http://github.com/dougwilson/perl5-test-override-useragent/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/dougwilson/perl5-test-override-useragent.git
version: 0.001
